name: CI with Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install Hub
      run: |
        brew install hub

    - name: Verify Hub Installation
      run: |
        hub version

    - name: Verify Docker Installation
      run: |
        docker --version

    - name: Verify Docker Compose Installation
      run: |
        docker-compose --version
